version: '3'

services:
  users:
    container_name: users
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6060:6060
    networks:
      - users
networks:
  users:
    external:
      name: netflix-network